# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Rajesh Nakarja
title: Chief Engineer of Wearable Hardware
email: raj@siliconwitchery.com
website: https://github.com/siliconwitch

# Social links
github_username:  siliconwitch
linkedin_username: rajesh-nakarja-embedded
twitter_username: siliconwitch
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Raj, and I'm Chief Engineer of Wearable Hardware at Silicon Witchery. I have previously worked for companies big and small, doing a variety of engineeing task such as designing robotics, automotive software and carrying out RF compliance.

  I am most skilled in: <mark>Hardware</mark> and <mark>Firmware</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in hardware engineering, some of my other interests and hobbies are:
   - Classic Car & Bike Restoration
   - Renaissance Fairs
   - Space & Science
   - [Athletic Pole Dance](https://www.instagram.com/siliconwitch.pole/)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
