# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Rajesh Nakarja
title: Chief Engineer of Wearable Hardware
email: raj@siliconwitchery.com
website: https://github.com/siliconwitch

# Social links
twitter_username: siliconwitch
github_username:  siliconwitch
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: rajesh-nakarja-embedded
# pinterest_username: jekyll
# youtube_username: jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Raj, and I'm Chief Engineer of Wearable Hardware at Silicon Witchery Sweden. As well as executive management, I have worked for companies big and small, designing robotics, automotive software and carrying out RF compliance.

  I am most skilled in: <mark>Hardware</mark>, <mark>Firmware</mark> and <mark>Wireless</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in hardware engineering, some of my other interests and hobbies are:
   - Athletic Pole Dance
   - Car/Bike Restoration
   - Renaissance Fairs
   - Space & Science

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
